while True:
    num_postes=int(input())
    if(num_postes==0):
        break
    np=[]
    npostes=0
    aux=0
    gatilho=False
    port=False
    distribuicao_postes=input().split()
    for passo in range(len(distribuicao_postes)):  
        if(distribuicao_postes[passo]=="1"):
            np.append(int(npostes/2))
            npostes=0
            if(port==False):
                port=True
        if(distribuicao_postes[passo]=="0"):
            if(port==False):
                npostes+=1
                aux+=1
            elif(port==True):
                npostes+=1
    snp=sum(np)
    if(npostes>0):
        gatilho=True
    if(gatilho==False):
        print(snp)
    else:
        npostes+=aux
        snp=(snp-int(aux/2))+int(npostes/2)
        print(int(snp))